# Site settings
title: Wynn Netherland
email: wynn.netherland@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Wynn Netherland
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://wynn.fm" # the base hostname & protocol for your site
twitter_username: pengwynn
github_username:  pengwynn

# Build settings
markdown: kramdown
